version: '3.8'

services:
  python:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./themes/boilerplate/scripts:/app/scripts
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1 
    command: ["/bin/bash"]
