
[en]
  languageName = "English"
  title = "English Site Title"
  weight = 1
  contentDir = "content/en"
  baseURL = "https://example.com"
  [en.params]
    bcp47Lang = "en-us"
    description = "English site description"
    gaMeasurementID = "G-PROD7890123"

[de]
  languageName = "Deutsch"
  title = "Deutsche Site Title"
  weight = 2
  contentDir = "content/de"
  baseURL = "https://example.de"
  [de.params]
    bcp47Lang = "de"
    description = "Deutsche Seitenbeschreibung"
    gaMeasurementID = "G-GERMAN12345"

[sk]
  languageName = "Slovenčina"
  title = "Slovenský Názov Stránky"
  weight = 3
  contentDir = "content/sk"
  baseURL = "https://example.sk"
  [sk.params]
    bcp47Lang = "sk"
    description = "Slovenský popis stránky"
    gaMeasurementID = "G-SLOVAK67890"